[package]
name = "mipsi"
version = "0.1.0"
authors = ["kmgy"]
edition = "2018"
description = "A MIPS-32 simulator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
clap = "2.33.3"
