name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: rustup component add clippy

    - name: Build
      run: cargo build --verbose --all-targets

    - name: Run tests
      run: cargo test --verbose

    - name: clippy
      run: |
          cargo clippy --all-targets --all-features -- -W clippy::dbg_macro
          cargo clippy -- -W clippy::dbg_macro -D warnings

    - name: Run all example
      run: |
          chmod +x ./test.sh
          ./test.sh

